version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=Vijay@123
      - DB_NAME=myfile
      - DB_PORT=5432
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vijay@123
      POSTGRES_DB: myfile
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
